kind: pipeline
type: exec
name: default

environment:
  DOCKER_REPO=none
  LANG=en_US.UTF-8

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    commands:
      - pwd
      - echo $DRONE_WORKSPACE
      - echo $DRONE_COMMIT_SHA
      - cd /scratch/drone-cache
      - pwd
      - echo "building $${DRONE_GIT_HTTP_URL}, branch $${DRONE_REPO_BRANCH}"
      - export CACHE_DIR="$${DRONE_REPO_NAMESPACE}-$${DRONE_REPO_NAME}-$${DRONE_REPO_BRANCH}"
      - echo "CACHE_DIR $${CACHE_DIR}"
      - "[ -e $${CACHE_DIR} ] || git clone $${DRONE_GIT_HTTP_URL} $${CACHE_DIR}"
      - cd $${CACHE_DIR}
      - git checkout $${DRONE_REPO_BRANCH}
      - git pull
      - git checkout $DRONE_COMMIT_SHA
      - git submodule update --recursive --init
      - echo "export DOCKER_REPO=none" > local.sh
      - echo "export LANG=en_US.UTF-8" >> local.sh
      - cp conf/local.conf.sample conf/local.conf
      - echo 'IMAGE_CLASSES += "testimage testsdk"' >> conf/local.conf
      - echo 'INHERIT += "report-error"' >> conf/local.conf
      - echo 'TESTIMAGE_AUTO_qemuall = "1"' >> conf/local.conf
      - /bin/bash -c ". ./qemux86-64-envsetup.sh && bitbake yoe-simple-image"
