kind: pipeline
type: exec
name: default

environment:
  DOCKER_REPO=none
platform:
  os: linux
  arch: arm64

steps:
  - name: test
    commands:
      - ls
      - pwd
      - echo $DRONE_WORKSPACE
      - echo $DRONE_COMMIT_SHA
      - cd /scratch/drone-cache
      - pwd
      - echo "building $${DRONE_GIT_HTTP_URL}, branch $${DRONE_REPO_BRANCH}"
      - export CACHE_DIR="$${DRONE_REPO_NAMESPACE}-$${DRONE_REPO_NAME}-$${DRONE_REPO_BRANCH}"
      - echo "CACHE_DIR $${CACHE_DIR}"
      - "[ -e $${CACHE_DIR} ] || git clone $${DRONE_GIT_HTTP_URL} $${CACHE_DIR}"
      - cd $${CACHE_DIR}
      - git checkout $${DRONE_REPO_BRANCH}
      - git pull
      - git checkout $DRONE_COMMIT_SHA
      - git submodule update --recursive --init
      - echo "export DOCKER_REPO=none" > local.sh
      - . ./raspberrypi3-64-envsetup.sh
      - bitbake yoe-simple-image
