kind: pipeline
type: exec
name: default

environment:
  DOCKER_REPO=none
  LANG=en_US.UTF-8

platform:
  os: linux
  arch: arm64

clone:
  disable: false

trigger:
  branch:
    - master
    - feature-drone-exec-runner
  event:
    - push
    - pull_request

steps:
  - name: build
    commands:
      - echo "build number $DRONE_BUILD_NUMBER"
      - echo "building $${DRONE_GIT_HTTP_URL}, branch $${DRONE_REPO_BRANCH}"
      - git submodule update --recursive --init
      - echo "export DOCKER_REPO=none" > local.sh
      - echo "export LANG=en_US.UTF-8" >> local.sh
      - cp conf/local.conf.sample conf/local.conf
      - echo SSTATE_DIR = \"/scratch/sstate-cache\" >> conf/local.conf
      - echo TMPDIR = \"/scratch/tmp-$DRONE_BUILD_NUMBER\" >> conf/local.conf
      - echo IMAGE_CLASSES += \"testimage testsdk\" >> conf/local.conf
      - echo INHERIT += \"report-error rm_work\" >> conf/local.conf
      #- echo TESTIMAGE_AUTO_qemuall = \"1\" >> conf/local.conf
      - /bin/bash -c ". ./qemux86-64-envsetup.sh && bitbake yoe-simple-image"
      - /bin/bash -c "yoe_clean_sstate"
      - rm -rf /scratch/tmp-$DRONE_BUILD_NUMBER
