kind: pipeline
type: exec
name: default

environment:
  DRONE_WORKSPACE=/home/yocto/drone.io
platform:
  os: linux
  arch: arm64

steps:
  - name: test
    commands:
      - ls
      - pwd
      - echo $DRONE_WORKSPACE
