kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: arm64
  DRONE_WORKSPACE=/home/yocto/drone.io

steps:
  - name: test
    commands:
      - ls
      - pwd
      - echo $DRONE_WORKSPACE
