MACHINE = "p3737-0000-p3701-0005"
DISTRO = "yoe"
OE_FRAGMENTS:append = " meta-yoe/projects/jetson-agx-orin-devkit"
#####################################################################
# add project specific configuration below this line
#####################################################################
#require conf/distro/include/lto.inc
#DISTRO_FEATURES:append = " lto"
# set max loadavg equal to nr of cpus, same at 1.0 on 1 cpu machine
#PARALLEL_MAKE:append = " \
#-l ${@int(os.sysconf(os.sysconf_names['SC_NPROCESSORS_ONLN'])) * 150/100} \
#"

# Setting a user/password in system
#INHERIT += "extrausers"
#EXTRA_USERS_PARAMS += "\
#    useradd admin; \
#    usermod -p '$(openssl passwd -6 myrootpassword)' admin; \
#    usermod -a -G adm admin; \
#    usermod -a -G video admin; \
#    usermod -a -G audio admin; \
#    usermod -a -G systemd-journal admin; \
#"
#EXTRA_IMAGE_FEATURES:remove = "allow-empty-password empty-root-password allow-root-login post-install-logging"

# For running oe-selftest uncomment below lines
#USER_CLASSES:remove = "buildhistory"
#PRSERV_HOST = ""
