MACHINE = "visionfive2"
DISTRO = "yoe"
OE_FRAGMENTS:append = " meta-yoe/projects/visionfive2"
#####################################################################
# add project specific configuration below this line
#####################################################################
#require conf/distro/include/lto.inc
#DISTRO_FEATURES:append = " lto"

# lld from upcoming 17.0 release is crashing for RISCV atm
#DISTRO_FEATURES:remove = "ld-is-lld"

# Setting a user/password in system
#INHERIT += "extrausers"
#EXTRA_USERS_PARAMS += "\
#    useradd admin; \
#    usermod -p '$(openssl passwd -6 myrootpassword)' admin; \
#    usermod -a -G adm admin; \
#    usermod -a -G video admin; \
#    usermod -a -G audio admin; \
#    usermod -a -G systemd-journal admin; \
#"
#EXTRA_IMAGE_FEATURES:remove = "allow-empty-password empty-root-password allow-root-login post-install-logging"

# For running oe-selftest uncomment below lines
#USER_CLASSES:remove = "buildhistory"
#PRSERV_HOST = ""
