MACHINE = "qemumips"
DISTRO = "yoe"
OE_FRAGMENTS:append = " meta-yoe/projects/qemucommon"
#####################################################################
# add project specific configuration below this line
#####################################################################
