MACHINE = "imx8mn-var-som"
DISTRO = "yoe"
OE_FRAGMENTS:append = " meta-yoe/projects/var-som-mx8m-nano"
#####################################################################
# add project specific configuration below this line
#####################################################################
#require conf/distro/include/lto.inc
#DISTRO_FEATURES:append = " lto"

# Setting a user/password in system
#INHERIT += "extrausers"
#EXTRA_USERS_PARAMS += "\
#    useradd admin; \
#    usermod -p '$(openssl passwd -6 myrootpassword)' admin; \
#    usermod -a -G adm admin; \
#    usermod -a -G video admin; \
#    usermod -a -G audio admin; \
#    usermod -a -G systemd-journal admin; \
#"
#EXTRA_IMAGE_FEATURES:remove = "allow-empty-password empty-root-password allow-root-login post-install-logging"

# For running oe-selftest uncomment below lines
#USER_CLASSES:remove = "buildhistory"
#PRSERV_HOST = ""

# the following is a hack to trick the imx-boot compile_mx8m function
# as Variscite is overriding do_compile but not setting the following var.
# This is likely a mismatch between the version of meta-freescale we are
# using vs Variscite
UBOOT_DTB_NAME_EXTRA = "imx8mn-var-som-symphony.dtb"
