MACHINE = "raspberrypi4-64"
DISTRO = "yoe"
OE_FRAGMENTS:append = " meta-yoe/projects/rpi-common"
#####################################################################
# add project specific configuration below this line
#####################################################################
PACKAGECONFIG:pn-wpebackend-rdk = "rpi"
# Use fkms for eglfs on RPI4 this enables both console display & graphics (for EGLFS)
# Otherwise use full kms
VC4DTBO = "${@bb.utils.contains_any('DISTRO_FEATURES', 'x11 wayland', 'vc4-kms-v3d', 'vc4-fkms-v3d', d)}"
#require conf/distro/include/lto.inc
#DISTRO_FEATURES:append = " lto"

# Setting a user/password in system
#INHERIT += "extrausers"
#EXTRA_USERS_PARAMS += "\
#    useradd admin; \
#    usermod -p '$(openssl passwd -6 myrootpassword)' admin; \
#    usermod -a -G adm admin; \
#    usermod -a -G video admin; \
#    usermod -a -G audio admin; \
#    usermod -a -G systemd-journal admin; \
#"
#EXTRA_IMAGE_FEATURES:remove = "allow-empty-password empty-root-password allow-root-login post-install-logging"

# For running oe-selftest uncomment below lines
#USER_CLASSES:remove = "buildhistory"
#PRSERV_HOST = ""
