BB_CONF_FRAGMENT_SUMMARY = "Common Raspberry Pi machine configuration"
BB_CONF_FRAGMENT_DESCRIPTION = "Shared build configuration for Raspberry Pi 4 (32-bit and 64-bit) and Raspberry Pi 5. Accepts Raspberry Pi firmware license flags, enables UART and I2C, configures initramfs bundle. \
"

YOE_PROFILE = "yoe-glibc-systemd-wayland"

# Acknowledge that Synaptics can revoke their license at any time on the
# Rapsberry pi firmware
LICENSE_FLAGS_ACCEPTED += "\
    synaptics-killswitch \
    nonfree_chexquest3 \
    nonfree_chexquest-galactic-conflict \
    "
# Enable serial console on Raspberry PI systems
ENABLE_UART = "1"

ENABLE_I2C = "1"

DISABLE_RPI_BOOT_LOGO = "1"

# Disable rpi raimbow screen
DISABLE_SPLASH = "1"

IMAGE_FSTYPES = "wic.xz wic.bmap ext4.xz tar.xz"
# Yoe Updater Supported Machines ( RPI, beaglebone, C4, SAMA5D27 for now )
INITRAMFS_IMAGE_BUNDLE = "1"
WKS_FILE = "yoe-sdimage.wks"
# Use yoe-initramfs-image for initramfs
INITRAMFS_IMAGE = "yoe-initramfs-image"
# Use kernel+initramfs image to boot
IMAGE_BOOT_FILES:remove = "${KERNEL_IMAGETYPE}"
IMAGE_BOOT_FILES:append = " ${KERNEL_IMAGETYPE}-initramfs-${MACHINE}.bin;${KERNEL_IMAGETYPE}"

# rpi (when not using u-boot )
IMAGE_BOOT_FILES:remove = "${KERNEL_IMAGETYPE};${SDIMG_KERNELIMAGE}"
IMAGE_BOOT_FILES:remove = "${KERNEL_IMAGETYPE}-initramfs-${MACHINE}.bin;${KERNEL_IMAGETYPE}"
IMAGE_BOOT_FILES:append = " ${KERNEL_IMAGETYPE}-initramfs-${MACHINE}.bin;${SDIMG_KERNELIMAGE}"

# Subprocess output:arm-yoe-linux-llvm-objcopy: error: Link field value 22 in section .rel.dyn is not a symbol table
OBJCOPY:pn-linux-raspberrypi:toolchain-clang = "${HOST_PREFIX}objcopy"

PACKAGECONFIG:pn-wpebackend-rdk:rpi = "rpi"
# Needed for Running bitbake -ctestimage <image>
TEST_TARGET_IP = "10.0.0.47"
TEST_SERVER_IP = "10.0.0.13"
TEST_TARGET = "simpleremote"
