header:
  version: 20

distro: "yoe"

repos:
  yoe-distro:
    path: .
    layers:
      sources/meta-yoe:

  openembedded-core:
    url: https://github.com/YoeDistro/openembedded-core
    branch: master
    path: layers/openembedded-core
    layers:
      meta:

  bitbake:
    url: https://github.com/YoeDistro/bitbake
    branch: master
    path: layers/bitbake
    layers:
      bitbake: disabled

  meta-openembedded:
    url: https://github.com/YoeDistro/meta-openembedded
    branch: master
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:
      meta-filesystems:
      meta-perl:
      meta-gnome:
      meta-initramfs:
      meta-webserver:
      meta-xfce:

  meta-qt6:
    url: https://github.com/YoeDistro/meta-qt6
    branch: yoe/6.10
    path: layers/meta-qt6

  meta-clang:
    url: https://github.com/YoeDistro/meta-clang
    branch: master
    path: layers/meta-clang
