name: YOE CI Loop

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up
        run: |
          git submodule update --recursive --init
          echo export DOCKER_REPO=none > local.sh
          echo export LANG=en_US.UTF-8 >> local.sh
          echo export SSTATE_CACHE_DIR=/scratch/sstate-cache >> local.sh
          cp conf/local.conf.sample conf/local.conf
          echo SSTATE_DIR = \"$SSTATE_CACHE_DIR\" >> conf/local.conf
          echo IMAGE_CLASSES += \"testimage testsdk\" >> conf/local.conf
          echo INHERIT += \"report-error rm_work\" >> conf/local.conf
          echo ERR_REPORT_SERVER = \"errors.yoctoproject.org\" >> conf/local.conf
          echo ERR_REPORT_PORT = \"80\" >> conf/local.conf
          echo ERR_REPORT_USERNAME = \"Drone Autobuilder\" >> conf/local.conf
          echo ERR_REPORT_EMAIL = \"info@yoedistro.org\" >> conf/local.conf
          echo TOOLCHAIN = \"clang\" >> conf/local.conf
          /bin/bash -c "sed -i -e 's/PACKAGE_FEED_URI.*$//' conf/site.conf"
          /bin/bash -c "sed -i -e 's/SDK_UPDATE_URL.*$//' conf/site.conf"
          /bin/bash -c "sed -i -e 's/backend=fbdev-backend.so.*$//' sources/openembedded-core/meta/recipes-graphics/wayland/weston-init/qemuall/weston.ini"
          /bin/bash -c ". ./qemuarm64-envsetup.sh && bitbake yoe-qt5-image"
          echo TESTIMAGE_AUTO_qemuall = \"1\" >> conf/local.conf
          /bin/bash -c ". ./qemuarm64-envsetup.sh && bitbake yoe-sdk-image"
          /bin/bash -c ". ./qemuarm64-envsetup.sh && resulttool report build/tmp/log/oeqa"
          /bin/bash -c ". ./qemuarm64-envsetup.sh && ./sources/openembedded-core/scripts/sstate-cache-management.sh -d-y"
